apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressapp-deployment
  namespace: kubernetes-cluster-deepakkumar07
  labels:
    app: expressapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: expressapp
  template:
    metadata:
      labels:
        app: expressapp 
    spec:
      containers:
      - name: expressserver
        image: deepak104080/test_local_express
        ports:
        - containerPort: 4000