apiVersion: v1
kind: Service
metadata:
  name: expressapp-service
  namespace: kubernetes-cluster-deepakkumar07
spec:
  selector:
    app: expressapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 4000
    nodePort: 31111